### ISSUE TITLE
brimcap analyze: unrecognizable file format

### ISSUE THREAD

**Issue by mattnibs** [brimdata/brimcap#119]
Currently if an analyze process outputs a file format that anyio.NewReader does not know how to read, it causes the entire command to error out. Instead of doing this, brimcap analyze should emit a warning prefixed by the command of the analyze process that outputs the unrecognizable file and proceed ahead.

**Comment by philrz** [comment]
Verified in Brimcap commit 97bb6fd.

Taking a step back, here's a repro of the original symptom back at Brimcap commit 0b1d433 that was right before the changes in the linked PR. In this case I've got a Homebrew-installed Suricata v6.0.3 on my Mac laptop and I've got a simple custom YAML to point at a wrapper script that invokes it.

```
$ cat custom-suricata.yml 
analyzers:
  - cmd: mysuricata
  
$ cat ~/bin/mysuricata 
#!/bin/bash
/usr/local/bin/suricata -r /dev/stdin
```

An off-the-shelf Suricata outputs other log files besides just the `eve.json` that contains the alerts (e.g. `fast.log`, `status.log`, and `suricata.log`) and these are of formats that Zed would choke on. Indeed, at Brimcap commit 0b1d433 it fails because of this. While it gives the name of the analyzer correctly as `mysuricata`, it doesn't provide any detail about the files it choked on. Also, the partial output it created happens to be corrupt enough to trigger a stack dump if we try to read it with `zq`, but I'll open a separate issue regarding that.

```
$ brimcap -version
Version: v0.0.6-8-g0b1d433

$ brimcap analyze -config custom-suricata.yml ../wrccdc.pcap > out.zng
100.0% 500.00MB/500.00MB records=14736 
mysuricata: format detection error
	tzng: line 1: invalid descriptor
	zeek: line 1: bad types/fields definition in zeek header
	zjson: line 1: invalid character '3' after top-level value
	zson: zson syntax error
	zng: zng type ID out of range
	csv: auto-detection not supported
	json: auto-detection not supported
	parquet: auto-detection not supported
	zst: auto-detection not supported
```

By comparison, at Brimcap commit 97bb6fd that has the benefit of this fix, we now are shown the Zed auto-detect errors as warnings, and the names of the choked-on log files are included in the messages. The output is a complete representation of the "good" data that Brimcap got from the analyzer, that being the `eve.json` data in this case.

```
$ brimcap -version
Version: v1.0.0-6-g97bb6fd

$ brimcap analyze -config custom-suricata.yml ../wrccdc.pcap > out.zng
mysuricata: fast.log: format detection error
	tzng: line 1: invalid descriptor
	zeek: line 1: bad types/fields definition in zeek header
	zjson: line 1: invalid character '3' after top-level value
	zson: zson syntax error
	zng: zng type ID out of range
	csv: auto-detection not supported
	json: auto-detection not supported
	parquet: auto-detection not supported
	zst: auto-detection not supported
mysuricata: stats.log: format detection error
	tzng: line 1: bad format
	zeek: line 1: bad types/fields definition in zeek header
	zjson: line 1: invalid character '-' in numeric literal
	zson: zson syntax error
	zng: zng type ID out of range
	csv: auto-detection not supported
	json: auto-detection not supported
	parquet: auto-detection not supported
	zst: auto-detection not supported
mysuricata: suricata.log: format detection error
	tzng: line 1: invalid descriptor
	zeek: line 1: bad types/fields definition in zeek header
	zjson: line 1: invalid character '/' after top-level value
	zson: zson syntax error
	zng: zng type ID out of range
	csv: auto-detection not supported
	json: auto-detection not supported
	parquet: auto-detection not supported
	zst: auto-detection not supported
100.0% 500.00MB/500.00MB records=672384 

$ echo $?
0

$ zq -z 'count() by event_type | sort -r' out.zng 
{event_type:"flow",count:395342 (uint64)} (=0)
{event_type:"alert",count:263307} (0)
{event_type:"dns",count:5664} (0)
{event_type:"http",count:3775} (0)
{event_type:"fileinfo",count:3719} (0)
{event_type:"tls",count:461} (0)
{event_type:"smb",count:86} (0)
{event_type:"anomaly",count:22} (0)
{event_type:"dcerpc",count:5} (0)
{event_type:"stats",count:3} (0)
```

Thanks @mattnibs!
