### ISSUE TITLE
Data ingestion crashes if system libmagic or /usr/bin/file is too new at Suricata analysis

### ISSUE THREAD

**Issue by drewsortega** [brimdata/brimcap#18]
**Describe the bug**
`/lib/brim/resources/app/zdeps/suricata/suricatarunner` currently uses a pre-included libmagic. This looks in `/etc/magic` and `/usr/share/misc/` for `magic/mgc`, with no way to configure it. This is problematic for two reasons:
1. Some linux distributions install `magic.mgc` in `/usr/share/file/misc/magic.mgc` instead of `/usr/share/misc/magic.mgc`, of which is specified at compile time for the `file` binary which builds system-level `libmagic`. As a result, when finishing ingesting data and running through suricata to generate alerts, brim will suddenly close the dataset with the following error:
```
Unable to generate full summary logs from PCAP 

Detail: /usr/lib/brim/resources/app/zdeps/suricata/suricatarunner exited with status 1: /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'

20/3/2021 -- 15:14:25 - <Error> - [ERRCODE: SC_ERR_MAGIC_LOAD(197)] - magic_load failed: could not find any valid magic files!
```
This is because it is in `/usr/share/file/misc/magic.mgc`, but there is no way to configure suricata in brim to look there without manually re-compiling the zdep with a different libmagic.
2. A somewhat okay workaround is to add a symlink to the magic file. For example:
```
/usr/share/misc/magic.mgc -> /usr/share/file/misc/magic.mgc
1 root root      30 Mar 20 15:19 magic.mgc -> /usr/share/file/misc/magic.mgc
```
This can technically work, however some distributions of linux have newer versions of `file` and `libmagic`. In this case, the following error can occur, if `magic.mgc` is too-new for the currently included suricata:
```
Unable to generate full summary logs from PCAP 

Detail: /usr/lib/brim/resources/app/zdeps/suricata/suricatarunner exited with status 1: 20/3/2021 -- 15:20:28 - <Error> - [ERRCODE: SC_ERR_MAGIC_LOAD(197)] - magic_load failed: File 5.32 supports only version 14 magic files. `/usr/share/misc/magic.mgc' is version 16
```
This happens because magic.mgc is compiled with file 5.39 which generates version 16 magic, but the included suricata uses file 5.32 and only supports version 14 and below.
**To Reproduce**
1. Install `file` configured to store magic in `/usr/share/file/misc`, for example like this PKGBUILD that Arch Linux uses: https://github.com/archlinux/svntogit-packages/blob/packages/file/trunk/PKGBUILD
2. Install brim by source or a binary .deb download.
3. Ingest a pcap in brim.
4. Wait for the entire pcap progress bar to load, then observe the error. Will be one of the two mentioned above.

**Expected behavior**
Suricata alerts are generated, and the pcap results are fully visible. Downloading an older version of file on the system in a fakeroot, compiling a new magic.mgc with version 14, and placing it in `/etc/share/misc/` is the only way that I've been able to get things to work as expected.

**Screenshots**
Data ingestion, for example this pcap (small window because included data is confidential), works file all the way until the progress bar gets to the end (fully loaded, then suricatarunner starts):
![](https://i.imgur.com/S9jFdNM.png)
Then, if magic is not stored in `/etc/magic` or `/etc/share/misc/magic` by system config, the following error occurs:
![](https://i.imgur.com/deRz9R4.png)
If you generate a magic file there or add a symlink to the correct magic file, you still get an error if the system-wide `libmagic` or `file` is too new, since it generates version 16 rather than version 14:
![](https://i.imgur.com/Uqxzn5O.png)

**Desktop Info**
 - OS: Arch Linux, with file 5.39 installed. 
 - Brim Version 0.24.0

**Comment by philrz** [comment]
I've verified in Brim commit 71b542c via nightly build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb) that this fix seems effective on Arch Linux.

In the following video, I've got an Arch Linux VM set up using `archlinux-2021.06.01-x86_64.iso`. With prior `v0.25.0` prerelease builds I was able to consistently reproduce the "could not find any valid magic files" error on this VM, but now I can import pcaps successfully without seeing the error.

https://user-images.githubusercontent.com/5934157/122650811-bbb39d00-d0e9-11eb-8e82-64f5caf56e70.mp4

**Comment by agonzal** [comment]
This is for 0.25.0-prerelease-95581f92.0 using the .deb for pkgBUILD. 
https://user-images.githubusercontent.com/8383391/123857200-df8b9580-d8d6-11eb-84b8-009757e9e17b.mp4

**Comment by philrz** [comment]
@agonzal: It looks like you may be one beta rev behind where this fix landed. That prerelease build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb) was posted in the **#beta** channel on Slack on June 16th, 2021 whereas the first beta build that was posted that had the fix was [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb) on June 19th, 2021, and that's the same build I used in the video a couple comments above where I verified it was working in my Arch Linux VM.

Just to make sure I have this all correct, I went ahead and confirmed that I also see a failure when I tried on my Arch Linux VM with the [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb) build that you were using. My error message is a little different than yours, but that may be down to our using pcaps. They both cite problems with "magic", hence they maintain the essence of the original issue.

![](https://user-images.githubusercontent.com/5934157/123868074-11572900-d8e4-11eb-892f-dd04a80e5106.png)

Since I'd already verified the fix with that [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-71b542c5.0/linux/Brim-0.25.0-prerelease-71b542c5.0.deb) build from June 19th, I went ahead and did yet another verification using the very latest beta build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-aa75b3f5.0/linux/Brim-0.25.0-prerelease-aa75b3f5.0.deb](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-aa75b3f5.0/linux/Brim-0.25.0-prerelease-aa75b3f5.0.deb) that was posted on June 25th, 2021, and that also worked for me, as I'd expect.

https://user-images.githubusercontent.com/5934157/123868207-41063100-d8e4-11eb-8f94-6049159f0acd.mp4

@agonzal: Could you try again on your Arch Linux with that newer build https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-aa75b3f5.0/linux/Brim-0.25.0-prerelease-aa75b3f5.0.deb? Thanks.

**Comment by agonzal** [comment]
I have the PKGBUILD already built so it will be easy to substitute the .deb
and report back. Will start shortly and report back. Thanks.

**Comment by agonzal** [comment]
I thought I grabbed the beta build that you tagged me in on Slack, but yes
this prerelease build does a complete import of a PCAP. I have not tested
ZSON or other formats as of right now, but I don't think you are
experiencing any issues there. Thanks again.
