### ISSUE TITLE
Linux cooked-mode capture (SLL) support

### ISSUE THREAD

**Issue by showipintbri** [brimdata/brimcap#19]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimsec/brim/wiki/Troubleshooting

**Describe the bug**
Loading a *.pcap file yielded this error

**To Reproduce**
Try to load the *.pcap file again

**Expected behavior**
The summary data generated by zeek should be produced

**Screenshots**
![image](https://user-images.githubusercontent.com/40892800/112165455-2295e880-8bc5-11eb-83c8-0eef22284677.png)

**Desktop Info**
[Please complete the following information]
 - OS: Windows 10
 - Brim Version: 0.24.0

**Comment by philrz** [comment]
It looks like another user has bumped into a variation of this problem as reported in a recent [community Slack thread](https://brimdata.slack.com/archives/C03MW6XT7HC/p1707748519979329). In this case the user was able to share their test data [traf2.pcap.gz](https://github.com/brimdata/brimcap/files/14246405/traf2.pcap.gz) which must be `gunzip`'ed before testing.

The attached video shows the user-facing symptom: The pcap can successfully dragged into Zui, but once we click on a connection and attempt to open its pcap slice in Wireshark, the "no packets found" error is shown.

https://github.com/brimdata/brimcap/assets/5934157/1b87f2df-5991-4789-acc3-669b07e01de6

Having looked closely at this repro, I can see conditions have changed slightly since is issue was first. In the past, the Zeek bundled with Brimcap/Zui was based on Zeek [v3.2.1](https://github.com/zeek/zeek/releases/tag/v3.2.0) which did not have support for cooked-mode/SLL. However, I can see support for this was added in Zeek [v5.1.0](https://github.com/zeek/zeek/releases/tag/v5.1.0), which explains why the Zeek summary logs are shown after the successful drag & drop. Meanwhile, Suricata quietly fails because they still lack support for this as tracked in their open issue [#4951](https://redmine.openinfosecfoundation.org/issues/4951).

```
$ suricata -r ../traf2.pcap 
i: suricata: This is Suricata version 7.0.2 RELEASE running in USER mode
E: pcap: datalink type 276 not (yet) supported in module PcapFile.
W: pcap: Failed to init pcap file ../traf2.pcap, skipping
E: pcap: pcap file reader thread failed to initialize
i: threads: Threads created -> RX: 1 W: 12 FM: 1 FR: 1   Engine started.
i: suricata: Signal Received.  Stopping engine.
```

Back to Zui/Brimcap, in my local Zui checkout I had it print out the `brimcap` command line that it's using to attempt to extract the pcap slice.

```
$ brimcap search -dst.ip 10.14.3.50 -dst.port 49668 -duration 22.121ms -proto tcp -src.ip 10.14.4.13 -src.port 49182 -ts 2022-03-05T11:46:54.963118Z -w /var/folders/fl/2wdg4knx65jb4xw3bjygdjsw0000gn/T/packets-2022-03-05T11_46_54.963118Z.pcap -root /Users/phil/work/zui/apps/zui/run/plugins/brimcap/storage/root
{"type":"error","error":"no packets found"}
```

However, recreating the equivalent filter logic in Wireshark we can see it has no problem isolating the slice. Wireshark also shows the evidence that the pcap is of the "cooked" variety.

![image](https://github.com/brimdata/brimcap/assets/5934157/db9a6a7a-81b1-4ff0-8967-bc28bac4eda2)

Finally, the Brimcap v1.6.0 that's bundled with current Zui releases does reflect that the link type is not currently supported.

```
$ ./brimcap -version

$ ./brimcap traf2.pcap 
Pcap type:         pcap
Pcap version:      2.4
Link type:         UnknownLinkType
Packet size limit: 262144
Number of packets: 95431
```

However, I do think I see a way to address this, so I will put up a Brimcap PR shortly.

**Comment by philrz** [comment]
Verified in Brimcap commit c74d4ff.

Using the test data from the last comment above, Brimcap is now able to detect the link type for this capture.

```
$ ./brimcap -version
Version: v1.6.0-13-gc74d4ff

$ ./brimcap info ~/Desktop/traf2.pcap 
Pcap type:         pcap
Pcap version:      2.4
Link type:         Linux SLL2
Packet size limit: 262144
Number of packets: 95431
```

Then with Zui `5d04fd3` that uses this Brimcap version, I can now successfully extract pcap slices from the user's "traf2.pcap" that failed in the past.

https://github.com/brimdata/brimcap/assets/5934157/2e6358bc-1ade-4751-8dc8-3a3e9292705e

All that said, after delivering this fix to the user, we learned that there's still a remaining issue here that seems to be specific to the Zeek port on Windows, so I've opened a separate issue https://github.com/zeek/zeek/issues/3609 to track that. There's also the problem cited above with how Suricata also lacks support for this link layer protocol, though that doesn't cause any failure to import the pcap into Zui, it just means no chance of seeing alerts. Ultimately it doesn't seem appropriate for us to maintain our own issues for every problem we encounter with one of the bundled analyzers, so I've opened #337 to track the idea of documenting somewhere (probably in the [Brimcap wiki](https://github.com/brimdata/brimcap/wiki)) what the known problems are that our users have hit with analyzers and link to the open issues for those other projects in the event that users want to pursue those.
