### ISSUE TITLE
How to generate zeek logs from pcap using cli?

### ISSUE THREAD

**Issue by AnixPasBesoin** [brimdata/brimcap#279]
I am a bit new to brimcap, and I would like to know if there is an option of generating zeek logs from pcaps?

**Comment by philrz** [comment]
@AnixPasBesoin: Yes, it can definitely do that. Brimcap incorporates a lot of [Zed](https://github.com/brimdata/zed) so if you run a pcap through Brimcap, by default it will generate logs from the analyzers that are bundled with it (Zeek, Suricata) and those logs can be in any output format that Zed supports (which includes Zeek TSV, but also JSON, Parquet, and others). The [Quickstart in the Brimcap README](https://github.com/brimdata/zed) kind of shows this, but it happens to use the ZNG output format that's the common binary format for Zed/Brim, so I can see why what you were seeking wasn't immediately obvious.

If for example you wanted to generate Zeek TSV logs from a pcap and output them with one log file per `_path` as is common with Zeek, a Brimcap command line would look like:

```
# brimcap analyze -f zeek -split logs MyPcap.pcap
```

...with the log files going into a subdirectory `logs/` that would be created. Note that by default it does generate Suricata logs, and these should be easy to spot because they'll have a numeric filename (e.g., `5.log`) because they lack a `_path` field like the Zeek logs have.

There's lots of flexibility here. For instance, the bundled Zeek and Suricata are admittedly kind of old at this point, so if you want to run newer ones or use different analyzers beyond just Zeek and/or Suricata (or not invoke Suricata at all), there's a [Custom Brimcap Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) article in the wiki that goes into detail on this.

I'll hold this issue open for a bit to see if you have any follow-on questions. Thanks for trying the Brim projects!

**Comment by AnixPasBesoin** [comment]
Thank you very much @philrz, I needed a starting point to further investigate `brimcap` and your answer does provide that :)).

**Comment by philrz** [comment]
Thanks for the update @AnixPasBesoin. I'll go ahead and close this issue. Feel free to add more comments or open a new issue if you need additional help, or you might also consider [joining our community Slack](https://www.brimdata.io/join-slack/) which is a great way to communicate with us and see what other users are up to.
